Repository Jaseci-Labs/slam, pull requests merged in 2024-03, with the labels that each got.

#11 Added Tutorial for Similarity Scorer Feature of Auto Evaluator
  docs/tutorials/similarity_scorer.md
Labels: documentation

#13 Implement Ranking Table Based on Win Percentage
  src/app.jac
  src/components/model_ranking.jac
Labels: enhancement

#4 Auto Evaluator (LLM Based)
  src/assets/criteria.prt.bak
  src/assets/prefer.prt.bak
  src/assets/promp_templates/criteria.prt
  src/assets/promp_templates/prefer.prt
  src/components/auto_eval.jac
  src/components/utils.jac
Labels: enhancement

#6 Tutorial on Running Human Evaluation
  docs/tutorials/human_eval.md
  docs/tutorials/insights_analystics.md
  docs/tutorials/response_generator.md
Labels: documentation

#16 Tutorial on How to Use LLM as an Evaluator
  README.md
  docs/tutorials/automatic_eval.md
Labels: documentation

#8 Graph Updates to Plotly
  .gitignore
  src/components/dashboard.impl.jac
  src/components/dashboard.jac
  src/components/emb_sim_scorer.jac
  src/components/model_ranking.jac
  src/components/plot_utils.jac
  src/components/py_utils.py
  src/components/utils.jac
Labels: enhancement

#18 Ability to Add Prompt Descriptions Straight from the Tool
  src/components/dashboard.impl.jac
  src/components/dashboard.jac
  src/components/llm_as_evaluator.impl.jac
  src/components/setup.impl.jac
  src/components/setup.jac
  src/components/utils.jac
Labels: enhancement

#21 [FEATURE] Ability to create, and edit criteria and their descriptions
  src/components/human_eval.impl.jac
  src/components/setup.impl.jac
  src/components/setup.jac
Labels: enhancement

#24 Query Engine is not working
  README.md
  query_engine.py
  requirements.dev.txt
  src/query_engine.impl.jac
  src/query_engine.jac
Labels: bug
